updateTimeout: 30000
tablePrefix: Interconomy_
vaultCurrency: gems
currencies:
  gems:
    defaultBalance: 1000
    alias:
      - gem
      - money
      - g
  crystals:
    defaultBalance: 0
    alias:
      - crystal
      - c