name: InterConomy
main: com.caxerx.mc.interconomy.InterConomy
version: 2.6.3
api-version: "1.13"
depend: [Vault, HyperNiteMC-Core]
commands:
 money:
  aliases: [balance, bal, gem, gems]
  description: "InterConomy command"
permissions:
  interconomy.check:
    default: true
    description: Check their own balance.
  interconomy.check.other:
    default: op
    description: Check others balance.
  interconomy.modify:
    default: op
    description: Modify balance of a player.
  interconomy.reload:
    default: op
    description: Reload plugin.