name: MultiConomy
main: com.ericlam.mc.multiconomy.MultiConomy
version: 2.6.3
api-version: "1.13"
depend: [Vault, HyperNiteMC-Core]
commands:
  money:
    aliases: [ gem, gems ]
    description: "MultiConomy command"
  balance:
    aliases: [bal]
    description: "MultiConomy balance command"
  multiconomy:
    aliases: [conomy, mconomy]
    description: "MultiConomy admin commands"
permissions:
  multiconomy.check:
    default: true
    description: Check their own balance.
  multiconomy.check.other:
    default: op
    description: Check others balance.
  multiconomy.modify:
    default: op
    description: Modify balance of a player.
  multiconomy.reload:
    default: op
    description: Reload plugin.