name: MultiConomy
main: com.ericlam.mc.multiconomy.MultiConomy
version: ${project.version}
api-version: "1.16"
depend: [HyperNiteMC-Core]
softdepend: [Vault]
commands:
  money:
    aliases: [ bal, balance ]
    description: "MultiConomy vault balance command"
  multiconomy:
    aliases: [conomy, mconomy]
    description: "MultiConomy admin commands"
permissions:
  multiconomy.check:
    default: true
    description: Check their own balance.
  multiconomy.check.other:
    default: op
    description: Check others balance.
  multiconomy.modify:
    default: op
    description: Modify balance of a player.
  multiconomy.reload:
    default: op
    description: Reload plugin.